services:
  - type: web
    name: kracken-server
    env: node
    plan: free
    rootDir: apps/server
    buildCommand: |
      # Install root dependencies first
      cd ../../ && npm install --include=dev
      # Install server dependencies
      npm install
      # Initialize database schema
      npm run init-db
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false

databases:
  - name: kracken-db
    databaseName: kracken_messenger
    user: kracken_user
    plan: free
